{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-htpasswd" (include "lsdserver.fullname" .) }}
  labels:
  {{- include "lsdserver.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ htpasswd .Values.auth.username .Values.auth.password  | b64enc | quote }}
{{- end }}