apiVersion: v2
name: readium-lcpserver
description: Readium Licence Server
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
- name: mysql
  version: "9.22.0"
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
