{{- if not .Values.certificate.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cert" (include "lcpserver.fullname" .) }}
  labels:
  {{- include "lcpserver.labels" . | nindent 4 }}
type: Opaque
data:
  cert.pem: {{ .Values.certificate.certificateBase64 }}
  key.pem: {{ .Values.certificate.privatekeyBase64 }}
{{- end }}