{{- if not .Values.certificate.existingSecret }}
{{- $defaultCert := .Files.Get "cert/cert.pem" | b64enc -}}
{{- $defaultKey := .Files.Get "cert/key.pem" | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cert" (include "lcpserver.fullname" .) }}
  labels:
  {{- include "lcpserver.labels" . | nindent 4 }}
type: Opaque
data:
  cert.pem: {{ .Values.certificate.certificateBase64 | default $defaultCert | quote }}
  key.pem: {{ .Values.certificate.privatekeyBase64 | default $defaultKey | quote }}
{{- end }}